spring:
  h2:
    console:
      enabled: true
      path: /h2-console 
  datasource:
    platform: h2
    url: jdbc:h2:file:~/projectdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
#    url: jdbc:postgresql://db:5432/postgres
#    username: postgres
#    password: mysecretpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#server:
#  port: 8443
#  ssl:
#    key-store-password: abc123
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-alias: tomcat
